apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: bonfire-image-2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bonfire-image-2
    app.kubernetes.io/part-of: bonfire-image-2
  name: bonfire-image-2
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: bonfire-image-2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: bonfire-image-2
    spec:
      containers:
      - image: quay.io/gbenhaim-apps/user1-tenant/bonfire-image-2/bonfire-image-2@sha256:bd6f05fefe919256e1eae0cabae67d24346b1dacf2c352dad9334812a706deca
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
